--- #YAML:1.0
name:                Socialtext-Wikrad
version:             0.06
abstract:            efficient wiki browsing and editing
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Curses::UI:                    0.95
    Socialtext::EditPage:          0.04
    Socialtext::Resting:           0.24
    Socialtext::Resting::Getopt:   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Luke Closs <cpan@5thplane.com>
