# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Socialtext-Wikrad
version:      0.02
version_from: lib/Socialtext/Wikrad.pm
installdirs:  site
requires:
    Curses::UI:                    0.95
    Socialtext::Resting:           0.19
    Socialtext::Resting::Getopt:   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
